# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: 
- main

pool: agents-mgmt

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

steps: 
- task: HelmInstaller@0
  inputs:
    helmVersion: '3.7.0'
    installKubectl: true
